/**
 * CSS class normalizer (DS-011, spec v2.1 §10, §12.1 and AC-22/AC-23).
 *
 * Class names are useful evidence but never authoritative identity: they may be semantic,
 * generic, utility-based, generated by CSS Modules/CSS-in-JS or hashed. This module keeps the
 * raw classes untouched for auditability and produces weighted tokens plus an explicit signal
 * strength that matching MUST corroborate with other evidence.
 */

export type ClassTokenCategory =
  | 'semantic'
  | 'variant'
  | 'state'
  | 'structural'
  | 'utility'
  | 'generated'
  | 'unknown';

export interface ClassToken {
  /** Original class the token came from (auditability). */
  raw: string;
  token: string;
  category: ClassTokenCategory;
  /** Relative weight 0..1 as matching evidence. */
  weight: number;
}

export interface ClassNormalizationResult {
  rawClasses: string[];
  tokens: ClassToken[];
  /** Deduplicated semantic/variant/state tokens ordered by descending weight. */
  semanticTokens: string[];
  /** Number of classes that contained at least one hash-like fragment. */
  hashedClassCount: number;
  /** Number of classes that produced at least one utility token. */
  utilityClassCount: number;
  /** Highest token weight observed (0 when there is no evidence at all). */
  signalStrength: number;
  /** True when no semantic/variant/state token was found. */
  onlyNoise: boolean;
}

/** DS-014 must cap the class contribution to this share of the total score (spec §12). */
export const CLASS_SIGNAL_WEIGHT_CAP = 0.1;

const CATEGORY_WEIGHT: Record<ClassTokenCategory, number> = {
  semantic: 1,
  variant: 0.8,
  state: 0.7,
  structural: 0.35,
  utility: 0.1,
  generated: 0.05,
  unknown: 0.2
};

const SEMANTIC_TOKENS = new Set([
  'button', 'btn', 'input', 'select', 'textarea', 'form', 'field', 'checkbox', 'radio', 'switch',
  'slider', 'card', 'modal', 'dialog', 'drawer', 'popover', 'tooltip', 'dropdown', 'menu', 'tab',
  'tabs', 'accordion', 'table', 'list', 'badge', 'chip', 'tag', 'avatar', 'icon', 'link', 'alert',
  'banner', 'toast', 'notification', 'header', 'footer', 'nav', 'sidebar', 'breadcrumb',
  'pagination', 'progress', 'spinner', 'loader', 'skeleton', 'label', 'legend', 'caption', 'text',
  'heading', 'title', 'paragraph', 'image', 'video', 'chart'
]);

const VARIANT_TOKENS = new Set([
  'primary', 'secondary', 'tertiary', 'ghost', 'outline', 'outlined', 'solid', 'filled', 'danger',
  'destructive', 'success', 'warning', 'info', 'neutral', 'inverse', 'subtle', 'elevated', 'flat',
  'compact', 'large', 'small', 'sm', 'md', 'lg', 'xl', 'xs'
]);

const STATE_TOKENS = new Set([
  'disabled', 'enabled', 'active', 'inactive', 'selected', 'checked', 'unchecked', 'loading',
  'hover', 'focus', 'focused', 'pressed', 'expanded', 'collapsed', 'open', 'closed', 'error',
  'invalid', 'valid', 'required', 'readonly'
]);

const STRUCTURAL_TOKENS = new Set([
  'wrapper', 'container', 'root', 'inner', 'outer', 'content', 'body', 'group', 'row', 'col',
  'column', 'stack', 'cluster', 'item', 'element', 'control', 'media', 'viewport'
]);

const GENERATED_TOKENS = new Set([
  'css', 'sc', 'jsx', 'emotion', 'styled', 'styles', 'style', 'svelte', 'vue', 'module', 'modules',
  'jss', 'make'
]);

const UTILITY_TOKEN_PATTERNS: readonly RegExp[] = [
  /^(flex|grid|block|inline|inline-block|inline-flex|hidden|contents|flow-root)$/,
  /^(static|fixed|absolute|relative|sticky)$/,
  /^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr|gap|space|w|h|min-w|max-w|min-h|max-h|size)(-|$)/,
  /^(text|font|leading|tracking|indent|whitespace|break|truncate)(-|$)/,
  /^(bg|border|ring|fill|stroke|divide|outline|shadow|opacity)(-|$)/,
  /^(rounded|z|order|basis|shrink|grow|overflow|inset|top|right|bottom|left|translate|scale|rotate|skew|origin|duration|delay|ease|animate|transition|transform|cursor|select|pointer|resize|appearance|sr-only|not-sr-only)(-|$)/,
  /^(justify|items|self|place|grid-cols|grid-rows|aspect)(-|$)/
];

const RESPONSIVE_PREFIX = /^(xs|sm|md|lg|xl|2xl|3xl|print):/;

const HASH_LIKE_PATTERNS: readonly RegExp[] = [
  /^\d+[a-z0-9]*$/,
  /^[a-z]?\d+[a-z0-9]*$/,
  /^[a-f0-9]{6,}$/,
  /^[a-z]{1,3}\d[a-z0-9]{2,}$/
];

export const isHashLikeToken = (token: string): boolean =>
  HASH_LIKE_PATTERNS.some((pattern) => pattern.test(token));

const splitIntoWords = (value: string): string[] =>
  value
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(/[\s_.:\-/]+/)
    .map((part) => part.toLowerCase())
    .filter((part) => part.length > 0);

const classifyToken = (token: string, raw: string, utilityClass: boolean): ClassToken => {
  const make = (category: ClassTokenCategory): ClassToken => ({
    raw,
    token,
    category,
    weight: CATEGORY_WEIGHT[category]
  });
  if (utilityClass) return make('utility');
  if (SEMANTIC_TOKENS.has(token)) return make('semantic');
  if (VARIANT_TOKENS.has(token)) return make('variant');
  if (STATE_TOKENS.has(token)) return make('state');
  if (STRUCTURAL_TOKENS.has(token)) return make('structural');
  if (GENERATED_TOKENS.has(token)) return make('generated');
  if (UTILITY_TOKEN_PATTERNS.some((pattern) => pattern.test(token))) return make('utility');
  if (isHashLikeToken(token)) return make('generated');
  return make('unknown');
};

const unique = (values: readonly string[]): string[] => [...new Set(values)];

/** Normalizes raw class names into auditable semantic tokens (spec §12.1). */
export function normalizeClassNames(classes: readonly string[]): ClassNormalizationResult {
  const rawClasses = classes.map((entry) => entry.trim()).filter((entry) => entry.length > 0);
  const tokens: ClassToken[] = [];
  const seen = new Set<string>();
  let hashedClassCount = 0;
  let utilityClassCount = 0;

  for (const raw of rawClasses) {
    const words = splitIntoWords(raw);
    if (words.length === 0) continue;
    const lowerRaw = raw.toLowerCase();
    // A class that *as a whole* is a layout/style utility (or a responsive variant of one)
    // describes styling, never identity: `text-sm` must not be read as the `text` component.
    const utilityClass =
      RESPONSIVE_PREFIX.test(lowerRaw) ||
      raw.includes(':') ||
      UTILITY_TOKEN_PATTERNS.some((pattern) => pattern.test(lowerRaw));
    let producedHash = false;
    let producedUtility = false;

    for (const word of words) {
      const token = classifyToken(word, raw, utilityClass);
      if (token.category === 'generated' && isHashLikeToken(word)) producedHash = true;
      if (token.category === 'utility') producedUtility = true;
      const key = `${raw}::${token.token}::${token.category}`;
      if (seen.has(key)) continue;
      seen.add(key);
      tokens.push(token);
    }

    if (producedHash) hashedClassCount += 1;
    if (producedUtility) utilityClassCount += 1;
  }

  const semanticTokens = unique(
    tokens
      .filter(
        (token) =>
          token.category === 'semantic' ||
          token.category === 'variant' ||
          token.category === 'state'
      )
      .sort((a, b) => b.weight - a.weight)
      .map((token) => token.token)
  );

  const signalStrength = tokens.reduce((max, token) => Math.max(max, token.weight), 0);

  return {
    rawClasses,
    tokens,
    semanticTokens,
    hashedClassCount,
    utilityClassCount,
    signalStrength,
    onlyNoise: semanticTokens.length === 0
  };
}
